# version: ‘3’
# services:
#  app:
#    container_name: morelooks
#    restart: always
#    build: .
#    ports:
#      - ‘80:3004’
#    links:
#      - postgres
#  postgres:
#    container_name: postgres
#    image: postgres
#    ports:
#      - ‘27017:27017’



version: "3"
services:
  app:
    container_name: myapp
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8080
    links:
      [postgres]

  postgres:
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    image: postgres
    environment: 
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
